  

server:
  port: 8081
  
  


spring:
 application:
    name: API-Gateway
 cloud:
    gateway:
      routes:
      - id: coupons
        uri: http://localhost:8083/
        predicates:
        - Path=/coupon/**
        
#      - id: buyer-service
#        uri: http://localhost:8084/
#        predicates:
#        - Path=/buyer/**

      - id: Admin-service
        uri: http://localhost:8084/
        predicates:
        - Path=/user/**
        

      - id: cart
        uri: http://localhost:8082/
        predicates:
        - Path=/cart/**
        
     
  
    

        
        
        
     
        
        


